routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes(['verify' => true]);

Route::middleware([ 'auth', 'verified'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/upcoming', [DashboardController::class, 'upcomingTasks'])->name('upcoming');
    Route::get('/complete', [DashboardController::class, 'completeTasks'])->name('complete');
    Route::get('/backlog', [DashboardController::class, 'backlogTasks'])->name('backlog');
    Route::get('/archived', [DashboardController::class, 'archivedTasks'])->name('archived');
    Route::resource('/tasks', TaskController::class);
    Route::patch('tasks/{task}/patch', [TaskController::class, 'patchTask'])->name('tasks.patch-status');
});

Route::get('/', [HomeController::class, 'index'])->name('home');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'due_date',
        'priority',
        'status',
        'assignee_id',
    ];

    public function assignee()
    {
        return $this->belongsTo(User::class, 'assignee_id');
    }

    public function sharedUsers()
    {
        return $this->belongsToMany(User::class, 'shared_tasks');
    }

    public function history()
    {
        return $this->hasMany(TaskHistory::class);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;
use Auth;
use Session;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        // get all the tasks
        $tasks = Task::where('assignee_id', Auth::user()->id)->get();

        // load the view and pass the tasks
        return view('tasks.index', ['name' => Auth::user()->name, 'tasks' => $tasks]);
//        return $tasks;
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('tasks.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        /* $validator */
        // store
        $task = new Task();
        $task->title = $request->input('title');
        $task->description = $request->input('description');
        $task->due_date = $request->input('due_date');
        $task->priority = $request->input('priority');
        $task->status = 'toDo';
        $task->assignee_id = $request->user()->id;
        $task->save();

//        return redirect()->route('tasks.index');
        // redirect
        Session::flash('message', 'Successfully created task!');
        return redirect('/tasks');
    }

    /**
     * Display the specified resource.
     */
    public function show(Task $task)
    {
        return view('tasks.show', ['name' => Auth::user()->name, 'task' => $task]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Task $task)
    {
        return view('tasks.edit', ['task' => $task]);
//        return $task;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Task $task)
    {

        $task->title = $request->input('title');
        $task->description = $request->input('description');
        $task->due_date = $request->input('due_date');
        $task->priority = $request->input('priority');
        $task->status = $request->input('status');
        $task->save();

//        return redirect()->route('tasks.show', $task);
        Session::flash('message', 'Updated task details!');
        return redirect('/tasks');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Task $task)
    {
        $task->delete();
        Session::flash('message', 'Task deleted!');
        return redirect('/tasks');
    }

    public function patchTask(Request $request, Task $task)
    {
         if(null !==$request->input('status')) $task->status = $request->input('status');
         elseif(null !==$request->input('priority')) $task->priority = $request->input('priority');
         $task->save();
        Session::flash('message', 'Updated task details!');
        return redirect('/tasks');
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('helmet')
    Add task
@endsection


@section('content')
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-header text-center">Create Task Form</div>
                        <div class="card-body">
                            <!-- will be used to show any messages -->
                            @if (Session::has('message'))
                                <div class="alert alert-info">{{ Session::get('message') }}</div>
                            @endif
                            {{--                            <p class="text-success text-center">{{Session::get('message')}}</p>--}}
                            <form action="{{ route('tasks.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row mb-3">
                                    <label for="title" class="col-md-3">Task Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" id="title" name="title" required/>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="description" class="col-md-3">Description</label>
                                    <div class="col-md-9">
                                        <textarea class="form-control" id="description" name="description" rows="3"
                                                  placeholder="write something to describe your task"></textarea>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    {{--                                    <label for="description" class="col-md-3">Due Date</label>--}}
                                    {{--                                    <div class="col-md-9">--}}
                                    {{--                                        <input type="text" class="form-control" name="due_date"/>--}}
                                    {{--                                    </div>--}}
                                    <label for="date" class="col-md-3 col-form-label">Date</label>
                                    <div class="col-md-9">
                                        <div class="input-group date" id="datepicker">
                                            <input type="datetime-local" class="form-control" id="date" name="due_date" required/>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="priority" class="col-md-3">Priority</label>
                                    <div class="col-md-9">
                                        <div class="input-group mb-3">
                                            <select class="form-select" id="priority" name="priority">
                                                {{--                                                <option selected>Choose...</option>--}}
                                                <option selected value="low"><span class="text-success">Low</span>
                                                </option>
                                                <option value="medium"><span class="text-warning">Medium</span></option>
                                                <option value="high"><span class="text-danger">High</span></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-3 mt-5">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-9">
                                        <input type="submit" class="btn btn-success px-5" name="btn"
                                               value="Create Task"/>
                                        <a href="{{route('tasks.index')}}" class="btn btn-secondary px-5">Cancel</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('helmet')
    Add task
@endsection


@section('content')
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-header text-center">Update Task Form</div>
                        <div class="card-body">
                            <!-- will be used to show any messages -->
                            @if (Session::has('message'))
                                <div class="alert alert-info">{{ Session::get('message') }}</div>
                            @endif
                            {{--                            <p class="text-success text-center">{{Session::get('message')}}</p>--}}
                            <form action="{{ route('tasks.update',['task'=>$task->id]) }}" method="POST" >
                                @csrf
                                @method('PUT')
                                <div class="row mb-3">
                                    <label for="title" class="col-md-3">Task Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" id="title" name="title" value="{{$task->title}}"/>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="description" class="col-md-3">Description</label>
                                    <div class="col-md-9">
                                        <textarea class="form-control" id="description" name="description" rows="3">{{$task->description}}</textarea>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="priority" class="col-md-3">Priority</label>
                                    <div class="col-md-9">
                                        <div class="input-group mb-3">
                                            <select class="form-select" id="priority" name="priority">
                                                {{--                                                <option selected>Choose...</option>--}}
                                                <option {{ $task->priority == 'low' ? 'selected' : '' }} value="low"><span class="text-success">Low</span></option>
                                                <option {{ $task->priority == 'medium' ? 'selected' : '' }} value="medium"><span class="text-warning">Medium</span></option>
                                                <option {{ $task->priority == 'high' ? 'selected' : '' }} value="high"><span class="text-danger">High</span></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="date" class="col-md-3">Due Date</label>
                                    <div class="col-md-9">
                                        <div class="input-group date" id="datepicker">
                                            <input type="datetime-local" class="form-control" id="date" name="due_date" value="{{$task->due_date}}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="status" class="col-md-3">Status</label>
                                    <div class="col-md-9">
                                        <div class="input-group mb-3">
                                            <select class="form-select" id="status" name="status">
                                                {{--                                                <option selected>Choose...</option>--}}
                                                <option {{ $task->status == 'toDo' ? 'selected' : '' }} value="toDo"><span class="text-success">To Do</span></option>
                                                <option {{ $task->status == 'inProgress' ? 'selected' : '' }} value="inProgress"><span class="text-warning">In-progress</span></option>
                                                <option {{ $task->status == 'completed' ? 'selected' : '' }} value="completed"><span class="text-danger">Completed</span></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-9">
                                        <input type="submit" class="btn btn-success px-5" name="btn" value="Update Task"/>
                                        <a href="{{route('tasks.index')}}" class="btn btn-secondary px-5">Cancel</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('helmet')
    All tasks
@endsection
{{--
<?php
echo '<pre>';
print_r($tasks);
echo '</pre>';
?>
--}}

@section('content')
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <p class="text-danger text-center my-1 fw-bold">{{Session::get('message')}} <span>&nbsp;</span></p>
                    <div class="card rounded-0">
                        <div class="card-header text-center fw-bolder h5">{{$task->title}} ({{$name}})</div>
                        <div class="card-body">
                            {{$task->description}}
                        </div>
                        <div>
                            <h5 class="card-subtitle">Associated persons;</h5>
                            <ul>
                                <li><img class="rounded-circle" src="{{$task->assignee->photo}}" alt="{{$task->assignee->name}}" title="{{$task->assignee->name}}" style="width: 32px;object-fit: cover"> </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="py-5 text-center">
                <a href="{{route('tasks.index')}}" class="btn btn-secondary px-5">Close</a>
            </div>
        </div>
    </section>
@endsection